### PR TITLE
propagate errors when decompressing; also unlink dstfile if we create

### PR DESCRIPTION
**Pull request by chipturner**
… it but fail to successfully compress or decompress

### CODE REVIEW

**Comment by Cyan4973** [comment]
Minor error from Visual : 

```
warning C4996: 'unlink': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _unlink. See online help for details. [C:\projects\zstd\visual\2013\zstd\zstd.vcxproj]
```

which gives : 
https://msdn.microsoft.com/en-us/en-en/library/ttcz0bys(v=vs.110).aspx

**Comment by Cyan4973** [comment]
minor note :

There is a subtlety with gzip decompression : 
using `gzip -dcf file` (or `zcat -f file` which is equivalent)
on a file _not_ compressed by `gzip`,
`gzip` is supposed to output verbatim the content of `file` instead of failing decompression.

I was told this was done to avoid breaking pipes containing both gzip and non-gzip content.

This is not yet supported by `zstd`, but when it will,
it will also be necessary to output an error code of zero for this specific case.

**Comment by Cyan4973** [comment]
Second note : 

I will also add a new test into the test suite
to cover this case (as it obviously wasn't up to now).

**Comment by chipturner** [comment]
Apparently `_unlink` doesn't exist in Linux.  Looks like `remove` will be sufficient and (hopefully) work on both platforms.

**Comment by Cyan4973** [comment]
It's also possible to special-case Visual with a `#define`, notably if `_unlink` on Windows has the same interface as `unlink` on Linux.

**Comment by Cyan4973** [comment]
Well, if that works fine with `remove`, let's use that :)

**Pull request merged**
