### PR TITLE
Allow building without legacy formats support, e.g. for embedded syst…

### PR DESCRIPTION
**Pull request by annulen**
…ems.

### CODE REVIEW

**Comment by Cyan4973** [comment]
Yes, that's a very good point Konstantin.
And your proposed modifications look pretty good to me.

Just a few minor details : 
- Contributions are never merged into master directly. They must go through "dev" branch or their own feature branches.
- The currently active feature branch is "newAPI". It will be merged into "dev" later this week.
The Makefile has been changed into this branch, hence it has a different history.
I recommend merging your modifications into it, otherwise there will be some conflicts.
- Alternatively, if you prefer, I can apply your changes manually into it.

Regards

**Comment by Cyan4973** [comment]
With "newAPI" branch now merged into "dev",
now seems a good time to add your PR into "dev" branch,
allowing building without legacy formats support.

Do you want to create a new PR @annulen ?

**Comment by Cyan4973** [comment]
It's now possible to build zstd without legacy support, using `ZSTD_LEGACY=disable`.

See b096cbf0d27af0cb7ff542e1f961b06532f68e2b

**Comment by annulen** [comment]
Thanks! I just didn't find time to check result of rebase

**Comment by annulen** [comment]
Out of curiosity, how soon can 0.4 be released?

**Comment by Cyan4973** [comment]
very soon ....

**Pull request closed without merging**
