### PR TITLE
Update brew for 0.7.4

### PR DESCRIPTION
**Pull request by chipturner**
Tested locally, installed 0.7.4 as expected.

### CODE REVIEW

**Comment by Cyan4973** [comment]
:+1:

**Comment by chipturner** [comment]
Confirmed this worked:

```
brew tap Cyan4973/zstd zstd
brew install zstd
```

Should we document this anywhere?

**Comment by chipturner** [comment]
CC @cadedaniel -- this is now live and usable externally, thanks for setting it up!

**Comment by Cyan4973** [comment]
> Should we document this anywhere?

Yes, likely in the readme

**Comment by cadedaniel** [comment]
Thanks to you guys for the extremely quick turnaround! Glad to see this live, will be using it in a project.

**Pull request merged**
