### PR TITLE
Move tests from zstd-playTests target to separate shell script.

### PR DESCRIPTION
**Pull request by annulen**
This patch allows me to run tests on MIPS board which lacks make.

### CODE REVIEW

**Comment by Cyan4973** [comment]
make-less platforms ? a new area for me ... ;)

The only minor issue is that I was considering to cut this test script into 2 parts,
one for "quick essential tests",
and the other one for longer tests, such as checking each compression level and very large file support.

Maybe this modification should be done first, so it's easier to see how to adapt it to make-less platforms ?

**Comment by annulen** [comment]
Well, I can build make for my platform, I just don't have it readily available, as I've never needed to have it on target before.
Also, I believe putting non-trivial shell constructs into makefile is extremely bad practice, all those $$ escapes and prohibition of empty lines hurt readability a lot

As an alternative to cutting script, we could add command line parameters to script

**Comment by Cyan4973** [comment]
Yes, it could be done this way

**Comment by annulen** [comment]
Which round-trip tests do you consider non-essential?

**Comment by Cyan4973** [comment]
Everything below and including 
`@./datagen -g270000000 | md5sum > tmp1`

**Comment by annulen** [comment]
Done

**Comment by Cyan4973** [comment]
Almost good !

For some reason, some of the tests are not present within `playTests.sh` : compression levels > 12 and huge file test are not in this list.

That being said, I can add them manually, the script design is simple enough

**Comment by annulen** [comment]
My bad

**Comment by Cyan4973** [comment]
All good !

**Pull request merged**
