### PR TITLE
Add simple python bindings

### PR DESCRIPTION
**Pull request by sergey-dryabzhinsky**

### CODE REVIEW

**Comment by sergey-dryabzhinsky** [comment]
It's buggy. Please wait till I fix it.

**Comment by sergey-dryabzhinsky** [comment]
Fixed

**Comment by Cyan4973** [comment]
Thanks Sergei

**Comment by Cyan4973** [comment]
By the way Sergey,
note that, usually (if using lz4 situation as an example),
python and other language wrappers tend to have their own project page,
which I link from homepage.

It's not an obligation, just for you to know this solution also exists, should you prefer it.
In my opinion, it has the advantage of providing the author some deserved visibility.

**Comment by sergey-dryabzhinsky** [comment]
Point taken.
Done - https://github.com/sergey-dryabzhinsky/python-zstd

**Comment by Cyan4973** [comment]
Great !

**Pull request closed without merging**
