### PR TITLE
Revert "minor fast mode improvement"

### PR DESCRIPTION
**Pull request by luben**
This reverts commit 96ffa424ebc4025744aaf95f3430a8142d94ec97.

Fixes issue #173

### CODE REVIEW

**Comment by luben** [comment]
... but it makes the compression ratio worse on the fast levels (compared 1 and 3)

**Comment by Cyan4973** [comment]
okay,
one of the issues I see with this patch, even though it works, is that `MINMATCH` used to mean `4` in the original version, while it means `3` in 0.6+ version. So the formula `(ip-(mlCode+MINMATCH)+2` has a different result.

Let's try to understand what's happening there...

**Comment by luben** [comment]
Completely agree. I just bisected the commit that has introduced this particular compression corruption and verified that reverting it fixes the issue. I agree that we should have better understanding why it happens and create a proper fix.

**Comment by luben** [comment]
Closing it as we agree this is not the right fix. At least we now know which change introduced the break.

**Pull request closed without merging**
