### PR TITLE
+ README Squash Compression Benchmark suite

### PR DESCRIPTION
**Pull request by tomByrer**
They already host your stuff, & seem to keep it updated.  Great for helping to choose a compression scenario.  Crazy how [many machines](https://quixdb.github.io/squash-benchmark/#choose-a-machine) they run tests on.

### CODE REVIEW

**Comment by Cyan4973** [comment]
We have an open issue with Evan regarding the validity of results displayed : 
https://github.com/quixdb/squash-benchmark/issues/17

I hope and expect we find a solution to this issue.
I'll then link to its website and even consider using squash to produce homepage benchmark figures.

**Comment by tomByrer** [comment]
Sounds like the best plan.  Yes results should be consistent.

I wonder if a squash fork without 'mmap', or at least easy to toggle, is possible.  Plus, I'm more interested in the compression of Internet text (JavaScript, JSON, HTML, SVG, fonts, etc) than compression of a dictionary.

**Comment by Cyan4973** [comment]
Waiting for Squash update, will open it again at that time

**Comment by tomByrer** [comment]
Sounds good, thanks

**Pull request closed without merging**
